/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.Product;

/**
 *
 * @author kiranreddy
 */
public class CreateJPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form Create
     */
    Product product;
    public CreateJPanel(Product product) {
        initComponents();
        this.product = product;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        lbldevid = new javax.swing.JLabel();
        lblmednum = new javax.swing.JLabel();
        txtlicnum = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtfaxnum = new javax.swing.JTextField();
        txthpnum = new javax.swing.JTextField();
        lblipnum = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        lblbanum = new javax.swing.JLabel();
        txtlinkdin = new javax.swing.JTextField();
        lbltelenum = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        lbldate = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        txtbanum = new javax.swing.JTextField();
        txtipnum = new javax.swing.JTextField();
        lbllicnum = new javax.swing.JLabel();
        txtdevid = new javax.swing.JTextField();
        lblgeodata = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        lblhpnum = new javax.swing.JLabel();
        lblfaxnum = new javax.swing.JLabel();
        lblvehid = new javax.swing.JLabel();
        txttelenum = new javax.swing.JTextField();
        txtssn = new javax.swing.JTextField();
        lbllinkdin = new javax.swing.JLabel();
        lblssn = new javax.swing.JLabel();
        txtvehid = new javax.swing.JTextField();
        txtmednum = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtdate = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtgeodata = new javax.swing.JTextArea();
        lblbiodata = new javax.swing.JLabel();
        lblimage = new javax.swing.JLabel();
        lblucode = new javax.swing.JLabel();
        txtucode = new javax.swing.JTextField();
        txtbiodata = new javax.swing.JButton();
        txtimage = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N

        lbldevid.setText("Device Identifier:");

        lblmednum.setText("Medical Record Number:");

        txtlicnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlicnumActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create Details");

        txtfaxnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfaxnumActionPerformed(evt);
            }
        });

        txthpnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthpnumActionPerformed(evt);
            }
        });

        lblipnum.setText("Internet Protocol:");

        lblemail.setText("EMAIL Address:");

        lblbanum.setText("Bank Account Number:");

        txtlinkdin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlinkdinActionPerformed(evt);
            }
        });

        lbltelenum.setText("Telephone number:");

        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        lbldate.setText("Date of Birth:");

        lblname.setText("Name:");

        txtbanum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbanumActionPerformed(evt);
            }
        });

        txtipnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtipnumActionPerformed(evt);
            }
        });

        lbllicnum.setText("License Number:");

        txtdevid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdevidActionPerformed(evt);
            }
        });

        lblgeodata.setText("Geographic data:");

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });

        lblhpnum.setText("Health Plan Benifitiary Number:");

        lblfaxnum.setText("FAX Number:");

        lblvehid.setText("Vehical Identifier:");

        txttelenum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelenumActionPerformed(evt);
            }
        });

        txtssn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtssnActionPerformed(evt);
            }
        });

        lbllinkdin.setText("Linkdin:");

        lblssn.setText("Socail Security Number:");

        txtvehid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvehidActionPerformed(evt);
            }
        });

        txtmednum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmednumActionPerformed(evt);
            }
        });

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });

        txtdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdateActionPerformed(evt);
            }
        });

        txtgeodata.setColumns(20);
        txtgeodata.setRows(5);
        jScrollPane3.setViewportView(txtgeodata);

        lblbiodata.setText("Biometric data:");

        lblimage.setText("Image:");

        lblucode.setText("Unique Code:");

        txtucode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtucodeActionPerformed(evt);
            }
        });

        txtbiodata.setText("Submit");
        txtbiodata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbiodataActionPerformed(evt);
            }
        });

        txtimage.setText("Submit");
        txtimage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtimageActionPerformed(evt);
            }
        });

        jLabel2.setText("(MM/DD/YYYY)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbltelenum)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbldate))
                            .addComponent(lblgeodata)
                            .addComponent(lblname)
                            .addComponent(lblfaxnum)
                            .addComponent(lblhpnum)
                            .addComponent(lblemail)
                            .addComponent(lblssn)
                            .addComponent(lblmednum)
                            .addComponent(lblbanum)
                            .addComponent(lbllicnum)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblvehid)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbllinkdin)
                                    .addComponent(lbldevid)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblipnum)
                                    .addComponent(lblbiodata)
                                    .addComponent(lblimage)
                                    .addComponent(lblucode))
                                .addGap(3, 3, 3)))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(txtname)
                                .addComponent(txttelenum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                .addComponent(txtdate, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                .addComponent(txtfaxnum, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                .addComponent(txtemail, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                .addComponent(txtmednum, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                .addComponent(txtssn, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                .addComponent(txthpnum, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                .addComponent(txtipnum, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                .addComponent(txtlinkdin, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                .addComponent(txtdevid, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                .addComponent(txtvehid, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                .addComponent(txtlicnum, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                .addComponent(txtbanum, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                .addComponent(txtucode, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                            .addComponent(txtbiodata, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtimage, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 81, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblgeodata, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldate, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltelenum, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttelenum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfaxnum)
                    .addComponent(txtfaxnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblemail, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblssn)
                    .addComponent(txtssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmednum)
                    .addComponent(txtmednum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblhpnum)
                    .addComponent(txthpnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbanum)
                    .addComponent(txtbanum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllicnum)
                    .addComponent(txtlicnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblvehid)
                    .addComponent(txtvehid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldevid)
                    .addComponent(txtdevid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllinkdin)
                    .addComponent(txtlinkdin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblipnum)
                    .addComponent(txtipnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbiodata)
                    .addComponent(txtbiodata))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblimage)
                    .addComponent(txtimage))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblucode)
                    .addComponent(txtucode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(btnsave)
                .addGap(171, 171, 171))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1216, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtlicnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlicnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlicnumActionPerformed

    private void txtfaxnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfaxnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfaxnumActionPerformed

    private void txthpnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthpnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthpnumActionPerformed

    private void txtlinkdinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlinkdinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlinkdinActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        boolean namevalid = this.validname(txtname.getText());
        boolean geovalid = this.validgeo(txtgeodata.getText());
        boolean datevalid = this.validdate(txtdate.getText());
        boolean televalid = this.validtele(txttelenum.getText());
        boolean faxvalid = this.validfax(txtfaxnum.getText());
        boolean ssnvalid = this.validssn(txtssn.getText());
        boolean emailvalid = this.validemail(txtemail.getText());
        boolean medrecvalid = this.validmedrec(txtmednum.getText());
        boolean healthvalid = this.validhealth(txthpnum.getText());
        boolean bankvalid = this.validbank(txtbanum.getText());
        boolean licevalid = this.validlice(txtlicnum.getText());
        boolean vehidvalid = this.validvehid(txtvehid.getText());
        boolean devicevalid = this.validdevice(txtdevid.getText());
        boolean ucodevalid = this.validucode(txtucode.getText());
        boolean ipnumvalid = this.validipnum(txtipnum.getText());
        boolean linkvalid = this.validlinkedin(txtlinkdin.getText());
        
        
        if( 
         namevalid  && datevalid && televalid && faxvalid
          && geovalid && ssnvalid && medrecvalid && healthvalid    
          && emailvalid 
          && bankvalid && licevalid && vehidvalid && devicevalid
          && ucodevalid && ipnumvalid && linkvalid
                ){
            this.product.setName(txtname.getText());
            this.product.setGeodata(txtgeodata.getText());
            this.product.setDob(txtdate.getText());
            this.product.setTelenum(txttelenum.getText());
            this.product.setFaxnum(txtfaxnum.getText());
            this.product.setEmail(txtemail.getText());
            this.product.setSsn(txtssn.getText());
            this.product.setMedrec(txtmednum.getText());
            this.product.setHpbnum(txthpnum.getText());
            this.product.setBanum(txtbanum.getText());
            this.product.setLicnum(txtlicnum.getText());
            this.product.setSernum(txtvehid.getText());
            this.product.setDevnum(txtdevid.getText());
            this.product.setLinkdin(txtlinkdin.getText());
            this.product.setIpaddr(txtipnum.getText());
            this.product.setucode(txtucode.getText());

            JOptionPane.showMessageDialog(this, "Details saved successfully");
        }
        else{
            
            System.out.println("enter valid data");
           
        }
        
        
    }//GEN-LAST:event_btnsaveActionPerformed

    private void txtbanumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbanumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbanumActionPerformed

    private void txtipnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtipnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtipnumActionPerformed

    private void txtdevidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdevidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdevidActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txttelenumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelenumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelenumActionPerformed

    private void txtssnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtssnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtssnActionPerformed

    private void txtvehidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvehidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvehidActionPerformed

    private void txtmednumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmednumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmednumActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdateActionPerformed

    private void txtucodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtucodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtucodeActionPerformed

    private void txtbiodataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbiodataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbiodataActionPerformed

    private void txtimageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtimageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtimageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblbanum;
    private javax.swing.JLabel lblbiodata;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lbldevid;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblfaxnum;
    private javax.swing.JLabel lblgeodata;
    private javax.swing.JLabel lblhpnum;
    private javax.swing.JLabel lblimage;
    private javax.swing.JLabel lblipnum;
    private javax.swing.JLabel lbllicnum;
    private javax.swing.JLabel lbllinkdin;
    private javax.swing.JLabel lblmednum;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblssn;
    private javax.swing.JLabel lbltelenum;
    private javax.swing.JLabel lblucode;
    private javax.swing.JLabel lblvehid;
    private javax.swing.JTextField txtbanum;
    private javax.swing.JButton txtbiodata;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtdevid;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfaxnum;
    private javax.swing.JTextArea txtgeodata;
    private javax.swing.JTextField txthpnum;
    private javax.swing.JButton txtimage;
    private javax.swing.JTextField txtipnum;
    private javax.swing.JTextField txtlicnum;
    private javax.swing.JTextField txtlinkdin;
    private javax.swing.JTextField txtmednum;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtssn;
    private javax.swing.JTextField txttelenum;
    private javax.swing.JTextField txtucode;
    private javax.swing.JTextField txtvehid;
    // End of variables declaration//GEN-END:variables
    //This validates the Name
    // Only alphabets are allowed 
    private boolean validname(String name){
        int i;
        int stringlen = name.trim().length();
        for(i = 0; i < stringlen; i++){
            if(!(Character.isAlphabetic(name.charAt(i)))){
                return false;
            }
        }
        return true;
    }
    //This validates the address
    // This will exclude all the below mentioned characters
    private boolean validgeo(String geodata){
        Pattern g = Pattern.compile("[-&+;=\\\\?@#|/'><.^*()%!-$]");
        int geolen = geodata.trim().length();
        if(geolen == 0 || (g.matcher(geodata).find() == true)){
            return false;
        }
        return true;
    }
    //This is for checking date format
    // This will also check for leap year as well
    private boolean validdate(String date){
        SimpleDateFormat d = new SimpleDateFormat("MM/dd/yyyy");
        d.setLenient(false);
        try{
            d.parse(date);
        }
        catch (ParseException D){
            return false;
        }
        return true;
    }  
    //This will validate the telephone number
    // This will not exclude 10 numbers
    private boolean validtele(String tele){
        int t;
        int telelen = tele.trim().length();
        if(telelen == 10){
            for(t = 0; t < telelen; t++){
                if(!(Character.isDigit(tele.charAt(t)))){
                    return false;
                }
            }
            return true;
        }
        return false;
    }
    //This is to validate fax number
    // Fax number is similar to phone number
    private boolean validfax(String fax){
        int f;
        int faxlen = fax.trim().length();
        if(faxlen == 10){
            for(f = 0; f < faxlen; f++){
                if(!(Character.isDigit(fax.charAt(f)))){
                    return false;
                }
            }
            return true;
        }
        return false;
    }
    // This will validate the email 
    private boolean validemail(String email){
        Pattern e = Pattern.compile("^(.+)@(.+)$");
        int emaillen = email.trim().length();
        if(emaillen != 0 && (e.matcher(email).find() == true)){
            return true;
        }
        return false;
    }
    // SSN is 9 digits and only digits
    // This is to validate SSN
    private boolean validssn(String ssn){
        int s;
        int ssnlen = ssn.trim().length();
        if(ssnlen == 9){
            for(s = 0; s < ssnlen; s++){
                if(!(Character.isDigit(ssn.charAt(s)))){
                    return false;
                }
            }
            return true;
        }
        return false;
    }
    // This will validate medical record
    // This is 6 digit
    private boolean validmedrec(String medrec){
        int m;
        int medlen = medrec.trim().length();
        if(medlen == 6){
            for(m = 0; m < medlen; m++){
                if(!(Character.isDigit(medrec.charAt(m)))){
                    return false;
                }
            }
            return true;
        }
        return false;
    }
    // This is similar to mobile number
    // This is 10 digit
    private boolean validhealth(String health){
        int h;
        int healen = health.trim().length();
        if(healen == 10){
            for(h = 0; h < healen; h++){
                if(!(Character.isDigit(health.charAt(h)))){
                    return false;
                }
            }
            return true;
        }
        return false;
    }
    // This is for bank details
    // Bank ID varies between 8 to 12 digits
    private boolean validbank(String bank){
        int b;
        int banklen = bank.trim().length();
        if((banklen >= 8) && (banklen <= 12)){
            for(b = 0; b < banklen; b++){
                if(!(Character.isDigit(bank.charAt(b)))){
                    return false;
                }
            }
            return true;
        }
        return false;
    }
    //drivers licence is 
    private boolean validlice(String licence){
        int l;
        int liclen = licence.trim().length();
        if(liclen == 10){
            for(l = 0; l < liclen; l++){
                if(!(Character.isDigit(licence.charAt(l)))){
                    return false;
                }
            }
            return true;
        }
        return false;
    }
    //This is alphanumeric
    private boolean validvehid(String vehical){
        int v;
        int vehlen = vehical.trim().length();
        if(vehlen == 6){
            for(v = 0; v < vehlen; v++){
                if((!(Character.isDigit(vehical.charAt(v)))) &&
                        (!(Character.isAlphabetic(vehical.charAt(v))))){
                    return false;
                }
            }
            return true;
        }
        return false;
    }
    // This is the IEMI number
    // this is the 15 digits
    private boolean validdevice(String device){
        int d;
        int devlen = device.trim().length();
        if(devlen == 15){
            for(d = 0; d < devlen; d++){
                if(!(Character.isDigit(device.charAt(d)))){
                    return false;
                }
            }
            return true;
        }
        return false;
    }
    // this is validate the unique number
    private boolean validucode(String unique){
        int u;
        int unlen = unique.trim().length();
        if(unlen == 6){
            for(u = 0; u < unlen; u++){
                if(!(Character.isDigit(unique.charAt(u)))){
                    return false;
                }
            }
            return true;
        }
        return false;
    }
    //This validates the IP address
    private boolean validipnum(String ipadd){
        Pattern i = Pattern.compile("(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])");
        int ipaddlen = ipadd.trim().length();
        if(ipaddlen != 0 && (i.matcher(ipadd).find() == true)){
            return true;
        }
        return false;
    }
    //This is to validate the linkedin profile
    private boolean validlinkedin(String linkedin){
        Pattern i = Pattern.compile("^https:\\/\\/[a-z]{2,3}\\.linkedin\\.com\\/.*$");
        int linklen = linkedin.trim().length();
        if(linklen != 0 && (i.matcher(linkedin).find() == true)){
            return true;
        }
        return false;
    }
}
