

package userinterface.RestaurantAdminRole;


import Business.EcoSystem;
import Business.Menu.Menu;
import Business.Restaurant.Restaurant;
import Business.Restaurant.RestaurantDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author  raunak
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    EcoSystem system;
    UserAccount ua;
    Restaurant resto;
    RestaurantDirectory restaurantDirectory;
    
    /** Creates new form AdminWorkAreaJPanel */
    public AdminWorkAreaJPanel(JPanel userProcessContainer,
                            UserAccount ua ,EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ua = ua;
        this.system = system;
        //valueLabel.setText();
        restaurantDirectory = system.getRestaurantDirectory();
        this.resto = restaurantDirectory.getRestaurant(ua);
        valueLabel.setText(this.resto.getRestaurantName());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnResturantInfo = new javax.swing.JButton();
        btnAddUpdateMenu = new javax.swing.JButton();
        btnAcceptDeclineOrders = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("My Work Area -Adminstrative Role");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        btnResturantInfo.setText("Manage Restaurant Info");
        btnResturantInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResturantInfoActionPerformed(evt);
            }
        });
        add(btnResturantInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 180, -1));

        btnAddUpdateMenu.setText("Add/Update menu");
        btnAddUpdateMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUpdateMenuActionPerformed(evt);
            }
        });
        add(btnAddUpdateMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 180, -1));

        btnAcceptDeclineOrders.setText("Accept/Decline Orders");
        btnAcceptDeclineOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptDeclineOrdersActionPerformed(evt);
            }
        });
        add(btnAcceptDeclineOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 180, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Restaurant :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 120, 30));

        valueLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 130, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnResturantInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResturantInfoActionPerformed
        // TODO add your handling code here:
        ManageRestaurantInfo manageRestObj = new ManageRestaurantInfo(this.userProcessContainer, 
                                    this.system, this.resto);  
        userProcessContainer.add("ManageMenu", manageRestObj);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnResturantInfoActionPerformed

    private void btnAddUpdateMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUpdateMenuActionPerformed
        try{
            this.resto.getMenu().getMenu();
        }catch(Exception e){
            Menu menuObj = new Menu();
            this.resto.setMenu(menuObj);
        }
        
        ManageMenu menuPanelObj = new ManageMenu(this.userProcessContainer, 
                                    this.system, this.resto);
        userProcessContainer.add("ManageRestaurantInfo", menuPanelObj);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAddUpdateMenuActionPerformed

    private void btnAcceptDeclineOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptDeclineOrdersActionPerformed
        ManageOrder manageOrderObj = new ManageOrder(this.userProcessContainer, 
                                    this.system, this.resto);
        userProcessContainer.add("ManageOrder", manageOrderObj);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnAcceptDeclineOrdersActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceptDeclineOrders;
    private javax.swing.JButton btnAddUpdateMenu;
    private javax.swing.JButton btnResturantInfo;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
    
}
